#define SYS_exit exit
#define SYS_read read
#define SYS_write write
#define SYS_open open
#define SYS_link link
#define SYS_unlink unlink
#define SYS_chdir chdir
#define SYS_mknod mknod
#define SYS_chmod chmod
#define SYS_getpid getpid
#define SYS_pause pause
#define SYS_access access
#define SYS_nice nice
#define SYS_sync sync
#define SYS_rename rename
#define SYS_mkdir mkdir
#define SYS_rmdir rmdir
#define SYS_dup dup
#define SYS_pipe pipe
#define SYS_acct acct
#define SYS_ioctl ioctl
#define SYS_setpgid setpgid
#define SYS_umask umask
#define SYS_dup2 dup2
#define SYS_getppid getppid
#define SYS_getpgrp getpgrp
#define SYS_setsid setsid
#define SYS_setrlimit setrlimit
#define SYS_getrusage getrusage
#define SYS_symlink symlink
#define SYS_readlink readlink
#define SYS_munmap munmap
#define SYS_fchmod fchmod
#define SYS_getpriority getpriority
#define SYS_setpriority setpriority
#define SYS_setitimer setitimer
#define SYS_getitimer getitimer
#define SYS_wait4 wait4
#define SYS_setdomainname setdomainname
#define SYS_uname uname
#define SYS_mprotect mprotect
#define SYS_getpgid getpgid
#define SYS_fchdir fchdir
#define SYS__newselect _newselect
#define SYS_msync msync
#define SYS_getsid getsid
#define SYS_fdatasync fdatasync
#define SYS_mlock mlock
#define SYS_munlock munlock
#define SYS_mlockall mlockall
#define SYS_munlockall munlockall
#define SYS_mremap mremap
#define SYS_poll poll
#define SYS_rt_sigqueueinfo rt_sigqueueinfo
#define SYS_pread64 pread64
#define SYS_pwrite64 pwrite64
#define SYS_getcwd getcwd
#define SYS_ugetrlimit ugetrlimit
#define SYS_mmap2 mmap2
#define SYS_truncate truncate
#define SYS_ftruncate ftruncate
#define SYS_stat stat
#define SYS_lstat lstat
#define SYS_fstat fstat
#define SYS_lchown32 lchown32
#define SYS_getuid32 getuid32
#define SYS_getgid32 getgid32
#define SYS_geteuid32 geteuid32
#define SYS_getegid32 getegid32
#define SYS_getgroups32 getgroups32
#define SYS_fchown32 fchown32
#define SYS_getresuid32 getresuid32
#define SYS_getresgid32 getresgid32
#define SYS_chown32 chown32
#define SYS_mincore mincore
#define SYS_madvise madvise
#define SYS_madvise1 madvise1
#define SYS_getdents64 getdents64
#define SYS_fcntl fcntl
#define SYS_exit_group exit_group
#define SYS_statfs64 statfs64
#define SYS_fstatfs64 fstatfs64
#define SYS_fadvise64_64 fadvise64_64
#define SYS_openat openat
#define SYS_mkdirat mkdirat
#define SYS_mknodat mknodat
#define SYS_fchownat fchownat
#define SYS_fstatat fstatat
#define SYS_unlinkat unlinkat
#define SYS_renameat renameat
#define SYS_linkat linkat
#define SYS_symlinkat symlinkat
#define SYS_readlinkat readlinkat
#define SYS_fchmodat fchmodat
#define SYS_faccessat faccessat
#define SYS_pselect6 pselect6
#define SYS_utimensat utimensat
#define SYS_fallocate fallocate
#define SYS_dup3 dup3
#define SYS_pipe2 pipe2
#define SYS_preadv preadv
#define SYS_pwritev pwritev
#define SYS_recvmmsg recvmmsg
#define SYS_prlimit64 prlimit64
#define SYS_sendmmsg sendmmsg
#define SYS_socket socket
#define SYS_socketpair socketpair
#define SYS_bind bind
#define SYS_connect connect
#define SYS_listen listen
#define SYS_accept4 accept4
#define SYS_getsockopt getsockopt
#define SYS_setsockopt setsockopt
#define SYS_getsockname getsockname
#define SYS_getpeername getpeername
#define SYS_sendto sendto
#define SYS_sendmsg sendmsg
#define SYS_recvfrom recvfrom
#define SYS_recvmsg recvmsg
#define SYS_shutdown shutdown
